Debugging article
cucumber/docs pull request #211
Opened 2018-08-01 16:13 UTC by olleolleolle

Same as #210.

2018-08-01 16:14 UTC, olleolleolle commented
@luke-hill I'm sorry, Git behaved badly towards me, and I re-opened a PR.

2018-08-02 07:16 UTC, mlvandijk reviewed
Thanks for getting this started @olleolleolle! Let's collaborate until it's sufficient to merge. If you & @luke-hill can do the Ruby, I can do the Java, and we'll have to find someone who could add the JavaScript.

2018-08-02 07:16 UTC, mlvandijk commented on content/cucumber/debugging.md
> +By setting an environment variable, you can cause Cucumber to use various debugging tools, and you can combine them by setting multiple environment variables.
replace "cause" with "tell"?

2018-08-02 07:16 UTC, mlvandijk commented on content/cucumber/debugging.md
> +1. Set a conditional breakpoint in the method `cucumber.runtime.Utils#invoke`, at the line `return targetMethod.invoke(target, args)` (line 40 in `cucumber-jvm` v1.2.5) and specify the following snip
Specify that this uses IntelliJ. Add something similar for Eclipse. (@olleolleolle if you're not familiar with Java, I can update this part myself)

2018-08-02 07:16 UTC, mlvandijk commented on content/cucumber/debugging.md
> +TBD.
Anyone available to add some JavaScript debugging tipcs? (note to self: check the Cucumber-js documentation)

2018-08-02 08:46 UTC, luke-hill approved these changes

2018-08-05 07:58 UTC, olleolleolle commented
@mlvandijk I don't know Eclipse with Java enough to create a new example for that, thanks for offering to improve that.

Should we see this as step 1, merge and continue in another debugging-with-JS-improving PR?

2018-08-05 12:18 UTC, mlvandijk commented
@olleolleolle I also don't know Eclipse that well (haven't used it in over a year), but I'm sure we can find some link like the one to IntelliJ.

2018-08-05 12:19 UTC, mlvandijk requested changes

2018-08-05 12:19 UTC, mlvandijk commented on content/cucumber/debugging.md
> +1. Set a conditional breakpoint in the method `cucumber.runtime.Utils#invoke`, at the line `return targetMethod.invoke(target, args)` (line 40 in `cucumber-jvm` v1.2.5) and specify the following snip
Just noticed this information is quite old (Cucumber v1.2.5 and IntelliJ 2017.1) - let's update to newer versions?

2018-08-07 07:48 UTC, olleolleolle commented
@mlvandijk You're pushing us closer to *done*!

2018-08-07 07:50 UTC, mlvandijk commented
Almost done @olleolleolle - will squash & merge any second now ;)
And I'll create a new issue for the JavaScript debugging

2018-08-07 08:00 UTC, xtrasimplicity commented on content/cucumber/debugging.md
> +1. Set a conditional breakpoint on th epart of the code you want to debug.
Just noticed that `the` has been split and joined `part` (`th epart`). :)

2018-08-07 08:10 UTC, merged