Added cucumberOptions
cucumber/docs pull request #227
Opened 2018-09-17 02:53 UTC by Shobika

CucumberOptions - dryRun, monochrome and strict properties were added

2018-09-17 12:46 UTC, mlvandijk requested changes
Thank you for this contribution! 
Just a few very minor edit requests for consistency only. Please let me know if you are ok to do these yourself (otherwise I'm happy to do them myself).

2018-09-17 12:46 UTC, mlvandijk commented on content/cucumber/api.md
> +@CucumberOptions(dryRun=true)
Please use a consistent formatting for the specified option for each of the three examples, either with or without spaces around the `=` sign.

2018-09-17 12:46 UTC, mlvandijk commented on content/cucumber/api.md
> +dryRun default value is false.
Please use a whole sentence starting with a capital letter, optionally marking the option and it's value, for instance: "The default option for `dryRun` is `false`. (Note: please do this consistently for all three options)

2018-09-17 12:46 UTC, mlvandijk commented on content/guides/browser-automation.md
> +   @Then("^the page title should start with \"(.*)\"$")
Nice catch, thanks!

2018-09-17 14:03 UTC, Shobika commented
Thank you for your feedback..I will do those changes myself and send a request again.

2018-09-17 22:24 UTC, Shobika commented
@mlvandijk finished updating.

2018-09-18 07:46 UTC, mlvandijk approved these changes

2018-09-18 07:46 UTC, merged

2018-09-18 07:46 UTC, aslakhellesoy commented
Hi @Shobika,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

2018-09-18 07:47 UTC, mlvandijk commented
Thanks for your contribution @Shobika !

2018-09-18 07:50 UTC, olleolleolle commented
Thanks, Shokbika for this! You're improving everyone's documentation experience!