Capitalization
cucumber/docs pull request #31
Opened 2017-09-23 16:19 UTC by Zearin

Another PR-with-lots-of-small changes.  This time, nearly 100% of the changes are simple capitalization.

2017-09-25 19:35 UTC, mlvandijk requested changes
Overall, these are great changes! Some minor details in the comments...

2017-09-25 19:35 UTC, mlvandijk commented on content/about/contributing.md
> +Before you [get in touch](/about/get-in-touch) and open a new Issue, make sure you have tried the latest gem. Also try to \[\[install]] the latest code from Git. This way you don't waste the develope
"version" instead of "gem"? (to make it more 'generic', i.e. not Ruby specific)

2017-09-25 19:35 UTC, mlvandijk commented on content/about/contributing.md
> +Before you [get in touch](/about/get-in-touch) and open a new Issue, make sure you have tried the latest gem. Also try to \[\[install]] the latest code from Git. This way you don't waste the develope
And also remove the [[]] around "install" (or there should be a link there).
Git should be GitHub.

2017-09-25 19:35 UTC, mlvandijk commented on content/about/contributing.md
> +Explain what gem you have (`gem list`), what command(s) you ran, what the output is, and so on.
"which version you are using" (instead of "what gem you have (`gem list`)")

2017-09-25 19:35 UTC, mlvandijk commented on content/about/contributing.md
> +Start by creating an Issue. Then, create a [Cucumber Feature](/gherkin/feature-introduction/) and start implementing it. It also helps if you add RSpec specs for the low level code.
"RSpec specs" should be ?

2017-09-25 19:35 UTC, mlvandijk commented on content/about/get-in-touch.md
> +Most people use Cucumber in more or less complex environments where a lot of other code is involved. Various web frameworks, many different ruby gems and your own code. There are many different ways
"ruby gems" should be ?

2017-09-25 19:35 UTC, mlvandijk commented on content/about/get-in-touch.md
>  - What other gems and versions you're using: `gem list`
"version" instead of "gem"

2017-09-25 19:35 UTC, mlvandijk commented on content/cucumber/running-features.md
> +Assuming you've installed Cucumber as a gem, run this at a command prompt to see the options for running Features:
"gem" should be ?

2017-09-25 19:35 UTC, mlvandijk commented on content/implementations/jvm.md
> +Please see the [General Reference](/gherkin/gherkin-reference/) for functionality common to all Cucumber implementations.
I really like using 'functionality' here, instead of "features" - which has a different meaning in this context :)

2017-09-25 19:35 UTC, mlvandijk commented on content/wiki/autotest-integration.md
> +If you get an error like `When using several—format options only one of them can be without a file (RuntimeError)` when running Features with autospec, you are probably accidentally requiring `spec`.
[[]] for "troubleshooting should be removed? (or a link provided).
(I thought I had already removed this link. Are you working of the latest master?)

2017-09-25 19:35 UTC, mlvandijk commented on content/wiki/cucumber-backgrounder.md
> +Always keep in mind that Cucumber is simply a DSL wrapper around the Ruby language, whose full expressiveness remains available to you in the Step Definition files (*but not in Feature files*). On th
There should be a working link to Gherkin here...

2017-09-25 19:35 UTC, mlvandijk commented on content/wiki/cucumber-backgrounder.md
> +In fact, this Step Definition should be further refactored into a method. The  method can reside in the same `.rb` file as the Step Definition. This both simplifies the step, and encourages the reuse
There are two spaces between "The  method"

2017-10-05 16:05 UTC, plaindocs commented
All of the changes @mlvandijk requested can be added in later I think - so I'm merging this for now.

2017-10-05 16:06 UTC, merged

2017-10-05 19:27 UTC, mlvandijk commented
@plaindocs My thoughts also. I fixed the textual stuff & links in new PR#37. Generalizing the docs from (mostly Ruby) specific to language agnostic remains to be done.

2017-10-06 10:09 UTC, plaindocs commented
Yeah, Generalizing the docs is much bigger issue than the mostly cosmetic fixes we've been doing recently.