Merge contributing docs
cucumber/docs pull request #35
Opened 2017-10-01 07:47 UTC by mlvandijk

Merge and update several contributing files to include information on how to contribute to the documentation.

2017-10-01 08:03 UTC, mlvandijk commented
Build fails due to external links in about/blog-posts.md;
not related to changes in this PR!

2017-10-05 16:01 UTC, plaindocs requested changes
Good stuff!

2017-10-05 16:01 UTC, plaindocs commented on content/about/contributing-to-documentation.md
> +(simple markup) and [AsciiDoc](http://toolchain.gitbook.com/syntax/asciidoc.html) (richer markup).
Aciidoc is no longer relevant here.

2017-10-05 17:17 UTC, mlvandijk commented
@plaindocs Thanks! I removed the bit about asciidocs...

2017-10-05 19:03 UTC, merged