Fix dead repository link to Java example
cucumber/docs pull request #355
Opened 2019-07-05 21:55 UTC by Riggs333

2019-07-05 21:58 UTC, Riggs333 commented
Sorry, I somehow missed seeing ticket #342 before creating the PR.
Feel free to reject this PR.

2019-07-17 12:35 UTC, mlvandijk requested changes
Could you update it in line with #342 please?

2019-07-31 07:46 UTC, luke-hill commented
@Riggs333 are you able to do this?

2019-09-10 10:42 UTC, mlvandijk reviewed
Added suggestion with link from #355 342

2019-09-10 10:42 UTC, mlvandijk commented on content/docs/tools/java.md
> +1.  Create a new Gradle project or look at [cucumber-java-skeleton](https://github.com/cucumber/cucumber-java-skeleton) example on Github
```suggestion
1.  Create a new Gradle project or look at [gradle-cucumber-runner](https://github.com/tsundberg/gradle-cucumber-runner) example on Github
```

2019-09-10 10:42 UTC, mlvandijk commented on content/docs/tools/java.md
> +1.  Create a new Gradle project or look at [cucumber-java-skeleton](https://github.com/cucumber/cucumber-java-skeleton) example on Github
@Riggs333 Are you able to commit the suggestion so we can merge your PR?

2019-10-10 15:24 UTC, Riggs333 commented
I'm very sorry for being this late to answer here and for applying the requested change.
@mlvandijk Would you please take a look if this is ok now?

2019-10-10 20:06 UTC, mlvandijk approved these changes

2019-10-10 20:06 UTC, mlvandijk commented
Thanks @Riggs333 !

2019-10-10 20:06 UTC, merged