Update api.md
cucumber/docs pull request #379
Opened 2019-09-10 18:56 UTC by Twalton1452

There is no documentation for javascript data tables

2019-09-11 08:14 UTC, luke-hill requested changes
The change is great, but could you add maybe just a short blurb. Even if it's just - Click here to find an example of a JS data-table

2019-10-08 07:09 UTC, luke-hill commented
Hi @Twalton1452 are you still working on this?

2019-10-08 17:28 UTC, mlvandijk requested changes

2019-10-08 17:28 UTC, mlvandijk commented on content/docs/cucumber/api.md
> +{{% text "javascript" %}}
Thanks for adding the link; please add even a brief description of what this will link to. Something like @luke-hill suggested is fine.

2019-12-29 08:09 UTC, merged

2019-12-29 08:09 UTC, aslakhellesoy commented
Hi @Twalton1452,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber