Update gherkin/reference.md
cucumber/docs pull request #420
Opened 2019-11-24 23:30 UTC by selfeki

- Adds missing link to `keyword` reference
Modifies explanations for clarity in the following sections: 
- Comments
- Example
- When
- Then
- And, But

2019-11-26 09:36 UTC, luke-hill requested changes
Minor change to one sentence. Other than that it reads nicely.

2019-11-26 09:36 UTC, luke-hill commented on content/docs/gherkin/reference.md
> +A comment must start on a new line. Comment lines are allowed anywhere in the file. They begin with zero or more spaces,
this sentence contradicts itself.

```
When I do something # a comment
```
As an example is ambiguous by this statement.

If you leave it as mentioned before. Or perhaps amend it to something like `Comments are only permitted at the start of a new line, anywhere in the feature file`

2019-12-29 10:48 UTC, mlvandijk commented on content/docs/gherkin/reference.md
> +Having too many steps within examples will cause them to lose their expressive power as specification and documentation.
```suggestion
Having too many steps in an example, will cause it to lose their expressive power as specification and documentation.
```

2019-12-29 10:48 UTC, mlvandijk commented on content/docs/gherkin/reference.md
> +A comment must start on a new line. Comment lines are allowed anywhere in the file. They begin with zero or more spaces,
```suggestion
Comments are only permitted at the start of a new line, anywhere in the feature file. They begin with zero or more spaces,
```

2019-12-29 10:49 UTC, mlvandijk commented on content/docs/gherkin/reference.md
> +An outcome *should* be on an **observable** output. That is, something that comes *out* of the system (report, user interface, message), and not a behaviour deeply buried inside the system (like a mi
```suggestion
An outcome *should* be on an **observable** output. That is, something that comes *out* of the system (report, user interface, message), and not a behaviour deeply buried inside the system (like a record in a database).
```

2019-12-29 10:49 UTC, mlvandijk commented on content/docs/gherkin/reference.md
> +You should only verify an outcome that is observable for the user (or external system), and changes to a database are usually not.
Nice catch, thanks!

2019-12-29 10:52 UTC, merged