[docs]Creating a PR for the docs as suggested
cucumber/docs pull request #53
Opened 2017-10-27 14:46 UTC by mgundala

@mlvandijk raised a PR for the docs can you have a quick review on these.

2017-10-28 06:09 UTC, mlvandijk requested changes
@mgundala Thanks for creating this PR! Overall a great addition.

2017-10-28 06:09 UTC, mlvandijk commented on content/bdd-introduction.md
> +    Let me try to explain with an example, A client wanted to increase his business by developing an important feature to his software.The Client gathered all his stake holders to the meeting where t
Remove the "Let me try to explain with an example" paragraph. Imho this paragraph does not add value in terms of explanation; the idea has already been clearly explained above.

2017-10-28 06:09 UTC, mlvandijk commented on content/bdd-introduction.md
> +   BDD focuses on obtaining a clear understanding of desired software behavior through discussion with stakeholders. It extends [TDD](docs/tdd-introduction) by writing test cases in a natural languag
"This allow the developers" should be "This allow**s** the developers"

2017-10-28 06:09 UTC, mlvandijk commented on content/tdd-introduction.md
> +    Test-driven development (TDD) is a software development process that relies on the repetition of a very short development cycle. Requirements are turned into very specific test cases, then the so
"re-factor to remove any duplication you see" replace with "re-factor as needed". As someone already mentioned there are many more refactorings than just DRY.

2017-11-04 13:05 UTC, haroon-sheikh requested changes

2017-11-04 13:05 UTC, haroon-sheikh commented on content/bdd-introduction.md
> +## Behavior-Driven Development(BDD):
can you add a space before the `(BDD)`

2017-11-04 13:05 UTC, haroon-sheikh commented on content/bdd-introduction.md
> +   BDD focuses on obtaining a clear understanding of desired software behavior through discussion with stakeholders. It extends [TDD](/tdd-introduction/) by writing test cases in a natural language t
Typo should be `behaviour`

2017-11-04 13:05 UTC, haroon-sheikh commented on content/bdd-introduction.md
> +   BDD focuses on obtaining a clear understanding of desired software behavior through discussion with stakeholders. It extends [TDD](/tdd-introduction/) by writing test cases in a natural language t
Do we want `minimises` or `minimizes`?

2017-11-04 13:05 UTC, haroon-sheikh commented on content/tdd-introduction.md
> +To get better understanding here we go life cycle of TDD
can you reword this? maybe just `TDD cycle:`

2017-11-04 18:40 UTC, olleolleolle commented on content/tdd-introduction.md
> +## Test Driven Development
Hyphenation needed: "Test Driven" => "Test-Driven".

2017-11-04 18:41 UTC, olleolleolle commented on content/tdd-introduction.md
> +  As the code base gradually increases in size, more and more attention is consumed by the re-factoring step. The design is constantly evolving and under constant review, though it is not predetermin
Hyphenation needed: "Test Driven" => "Test-Driven".

2017-11-04 18:43 UTC, olleolleolle commented
@mlvandijk I added tiny hyphenation notes as comments here.

2017-11-05 16:04 UTC, mlvandijk commented
@mgundala Edited the typos, hope you don't mind. I'd still like to propose removing the paragraph "Let me try to explain with an example" as I don't think this adds value to the already clear info.
Otherwise, I'd be happy to merge (if @olleolleolle and @haroon-sheikh agree?)

2017-11-08 08:45 UTC, merged

2017-11-08 08:45 UTC, aslakhellesoy commented
Hi @mgundala,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber