Inform Readers Of 10 Minute Tutorial Of Prerequisites
cucumber/docs pull request #666
Opened 2021-09-15 22:52 UTC by TomerPacific

Adding introduction bullets for java/kotlin/javascript/ruby

# Description

In order to better clarify that the 10 minute guides need some prior knowledge, several bullet points were added per language to demonstrate this.

# Motivation & context
Fixes #647 

## Type of change
- New feature (non-breaking change which adds new behaviour)

## Note to other contributors
N/A

# Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-15 22:53 UTC, TomerPacific commented
Once we agree upon the format for these bullets, there might be a need to consolidate the Java and Kotlin cases together.

2021-09-16 07:23 UTC, aurelien-reeves requested changes
The ending blocks are not ending 😄

But regarding the format and the content, it looks good to me 👍

2021-09-16 07:23 UTC, aurelien-reeves commented on content/docs/guides/10-minute-tutorial.md
> +{{% block %}}
```suggestion
{{% /block %}}
```

2021-09-16 07:23 UTC, aurelien-reeves commented on content/docs/guides/10-minute-tutorial.md
> +{{% block %}}
```suggestion
{{% /block %}}
```

2021-09-16 07:23 UTC, aurelien-reeves commented on content/docs/guides/10-minute-tutorial.md
> +{{% block %}}
```suggestion
{{% /block %}}
```

2021-09-16 07:23 UTC, aurelien-reeves commented on content/docs/guides/10-minute-tutorial.md
> +{{% block %}}
```suggestion
{{% /block %}}
```

2021-09-16 11:03 UTC, TomerPacific commented on content/docs/guides/10-minute-tutorial.md
> +{{% block %}}
Have corrected ending blocks.

2021-09-16 12:07 UTC, aurelien-reeves requested changes

2021-09-16 12:07 UTC, aurelien-reeves commented on content/docs/guides/10-minute-tutorial.md
> +
```suggestion
Please be aware that this tutorial assumes that you have a:

{{% block "java" %}}
* Basic understanding of the Java programming language
* Basic understanding of the Gradle file
{{% /block %}}
{{% block "kotlin" %}}
* Basic understanding of the Kotlin programming language
* Basic understanding of the Gradle file
{{% /block %}}
{{% block "javascript" %}}
* Basic understanding of the Javascript programming language
{{% /block %}}
{{% block "ruby" %}}
* Basic understanding of the Ruby programming language
* Basic understanding of the Bundler tool and `Gemfile`
{{% /block %}}
* Some experience using a terminal
* Some experience using a text editor

```
Blank lines in a list are generating extra paragraph and new lists in the resulting HTML

2021-09-16 12:09 UTC, aurelien-reeves commented
FYI in the "checks" list, if you click the "Details" link for "netlify/cucumber/deploy-preview", you can see a preview of your changes. You'll eventually just have to put "/docs" manually at the end of the URL.

2021-09-16 12:32 UTC, TomerPacific commented
@aurelien-reeves , your proposed changes unformatted the lists and they appear as *. Working on sorting it out.

2021-09-16 12:33 UTC, aurelien-reeves commented
> Working

Yeap, just noticed that too.

I guess maybe just adding a blank line right before the "some experience using a terminal" might fix this

2021-09-16 12:52 UTC, aurelien-reeves approved these changes

2021-09-17 09:30 UTC, TomerPacific commented
@aurelien-reeves , thank you for your patience and for reviewing this PR. What is the process now after this PR has been approved? Should I merge it?

2021-09-17 09:40 UTC, aurelien-reeves commented
Yes, you can merge
It will be deployed automatically to production

2021-09-17 10:54 UTC, merged

2021-09-20 06:51 UTC, aurelien-reeves commented
Thanks @TomerPacific for your contribution 🎉