docs: add Go to the documentation
cucumber/docs pull request #709
Opened 2021-12-20 12:16 UTC by mdelapenya

# Description

This PR is adding examples on how to organise the Go code using [godog](https://github.com/cucumber/godog), the official implementation of Cucumber in Go.

# Motivation & context

I was following the tutorial, trying to reuse some parts for an internal tutorial and missed the Go version, as we are using it internally.

## Type of change

- Docs: add documentation for Go

_Remember to add an entry to the relevant section of CHANGELOG.md as part of this pull request._

## Note to other contributors

_If your change may impact future contributors, explain it here, and remember to update README.md and CONTRIBUTING.md accordingly._

## Update required of cucumber.io/docs

_If the [Cucumber documentation](https://cucumber.io/docs/) will require an update,
submit an issue or ideally a pull request to [cucumber/docs](https://github.com/cucumber/docs/) and
reference it here._

_e.g. "Ref: cucumber/docs/pull/#99"_

# Checklist:

- [ ] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

2021-12-20 12:18 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> +This is either the default case or the location specified with the {{% text "java,kotlin" %}}relevant{{% /text %}}{{% text "javascript" %}}relevant{{% /text %}}{{% text "ruby" %}}`-r`{{% /text %}}{{%
```suggestion
This is either the default case or the location specified with the {{% text "java,kotlin" %}}relevant{{% /text %}}{{% text "javascript" %}}relevant{{% /text %}}{{% text "ruby" %}}`-r`{{% /text %}}{{% text "go" %}}relevant{{% /text %}} option.
```

2021-12-20 12:23 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> + - go
```suggestion
 - golang
```

2021-12-20 12:23 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> +This means that anything ending in {{% text "java" %}}`.java`{{% /text %}}{{% text "kotlin" %}}`.kt`{{% /text %}}{{% text "javascript" %}}`.js`{{% /text %}}{{% text "ruby" %}}`.rb`{{% /text %}}{{% te
```suggestion
This means that anything ending in {{% text "java" %}}`.java`{{% /text %}}{{% text "kotlin" %}}`.kt`{{% /text %}}{{% text "javascript" %}}`.js`{{% /text %}}{{% text "ruby" %}}`.rb`{{% /text %}}{{% text "golang" %}}`.go`{{% /text %}}
```

2021-12-20 12:23 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> +This is either the default case or the location specified with the {{% text "java,kotlin" %}}relevant{{% /text %}}{{% text "javascript" %}}relevant{{% /text %}}{{% text "ruby" %}}`-r`{{% /text %}}{{%
```suggestion
This is either the default case or the location specified with the {{% text "java,kotlin" %}}relevant{{% /text %}}{{% text "javascript" %}}relevant{{% /text %}}{{% text "ruby" %}}`-r`{{% /text %}}{{% text "golang" %}}relevant{{% /text %}} option.
```

2021-12-20 12:23 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> +Instead, we recommend creating a separate{{% text "ruby" %}} `*_steps.rb`{{% /text %}}{{% text "java" %}} `StepDefinitions.java`{{% /text %}}{{% text "kotlin" %}} `StepDefinitions.kt`{{% /text %}}{{%
```suggestion
Instead, we recommend creating a separate{{% text "ruby" %}} `*_steps.rb`{{% /text %}}{{% text "java" %}} `StepDefinitions.java`{{% /text %}}{{% text "kotlin" %}} `StepDefinitions.kt`{{% /text %}}{{% text "javascript" %}} `*_steps.js`{{% /text %}}{{% text "golang" %}} `*_steps.go`{{% /text %}} file for each domain concept.
```

2021-12-20 12:23 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> +A good rule of thumb is to have one file for each major {{% text "ruby" %}}model/database table.{{% /text %}}{{% text "java,kotlin" %}}domain object.{{% /text %}}{{% text "javascript" %}}domain objec
```suggestion
A good rule of thumb is to have one file for each major {{% text "ruby" %}}model/database table.{{% /text %}}{{% text "java,kotlin" %}}domain object.{{% /text %}}{{% text "javascript" %}}domain object.{{% /text %}}{{% text "golang" %}}domain object.{{% /text %}}
```

2021-12-20 12:23 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> +The first three files would define all the `Given`, `When`, and `Then` step definitions related to creating, reading, updating, and deleting the various {{% text "ruby" %}}models.{{% /text %}}{{% tex
```suggestion
The first three files would define all the `Given`, `When`, and `Then` step definitions related to creating, reading, updating, and deleting the various {{% text "ruby" %}}models.{{% /text %}}{{% text "java,golang" %}}types of objects.{{% /text %}}{{% text "javascript" %}}types of objects.{{% /text %}}
```

2021-12-20 12:23 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> +{{% block "go" %}}
```suggestion
{{% block "golang" %}}
```

2021-12-20 12:23 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> +{{% text "java,kotlin,go" %}}We suggest taking a look at the [Factory Design Pattern] (https://refactoring.guru/design-patterns/factory-method) as well.{{% /text %}}
```suggestion
{{% text "java,kotlin,golang" %}}We suggest taking a look at the [Factory Design Pattern] (https://refactoring.guru/design-patterns/factory-method) as well.{{% /text %}}
```

2021-12-20 12:23 UTC, mdelapenya commented on content/docs/gherkin/step-organization.md
> +The method can reside in the same {{% text "java" %}}`.java`{{% /text %}}{{% text "kotlin" %}}`.kt`{{% /text %}}{{% text "javascript" %}}`.js`{{% /text %}}{{% text "ruby" %}}`.rb`{{% /text %}}{{% tex
```suggestion
The method can reside in the same {{% text "java" %}}`.java`{{% /text %}}{{% text "kotlin" %}}`.kt`{{% /text %}}{{% text "javascript" %}}`.js`{{% /text %}}{{% text "ruby" %}}`.rb`{{% /text %}}{{% text "golang" %}}`.go`{{% /text %}} file as the step definition.
```

2021-12-27 08:49 UTC, aurelien-reeves commented
Great idea, great PR! 

I agree to merge it as-is and to follow-up with other PR for adding go-lang to other pages.
But I just would like to wait for other contributors opinion on that :p

2021-12-27 08:49 UTC, aurelien-reeves approved these changes

2021-12-27 08:51 UTC, aurelien-reeves requested changes
The golang logo is missing actually 😅

2021-12-27 08:53 UTC, aurelien-reeves commented
> 



> The golang logo is missing actually 😅

Oh, actually it is not missing, sorry for that 😓

2021-12-27 08:53 UTC, aurelien-reeves approved these changes

2022-02-03 08:45 UTC, merged

2022-02-03 08:45 UTC, aslakhellesoy commented
Hi @mdelapenya,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber