Add note to use same version numbers
cucumber/docs pull request #76
Opened 2017-11-11 06:49 UTC by mlvandijk

Should solve #17

2017-11-11 07:51 UTC, aslakhellesoy requested changes
Can you convert this into a `{{% tip %}}` box instead?

Or better, make a red `{{% note %}}` box. Copy the `tip.html` shortcode to `note.html` and style it with red. See bulma docs for what css class to use.

2017-11-11 20:32 UTC, mlvandijk commented
@aslakhellesoy I've added a {{% note %}} shortcode and tagged the notes as such. 
Red was a bit much imho, so I opted to style in black ('is-dark') for now. Found the bulma info: https://bulma.io/documentation/components/message :)

2017-11-11 21:55 UTC, olleolleolle commented on themes/cucumber-hugo/layouts/shortcodes/tip.html
> +<article class="message is-primare">
Is this a typo or the real class name?

2017-11-12 09:38 UTC, olleolleolle commented
Looks good now!

2017-11-14 15:35 UTC, merged